name: ROS2 CI
on:
  push:
    branches:
      - ros2
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  industrial_ci:
    strategy:
      matrix:
        ROS_DISTRO: [humble, iron, rolling]
        ROS_REPO: [testing, main]
        CMAKE_ARGS: ['-DCMAKE_BUILD_TYPE=Debug', '-DCMAKE_BUILD_TYPE=Release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REP: ${{ matrix.ROS_REPO }}
          CMAKE_ARGS: ${{ matrix.CMAKE_ARGS }}
